### ISSUE TITLE
Support for images

### ISSUE THREAD

**Issue by orschiro** [davidmhewitt/clipped#23] opened 2018-01-24 16:29 UTC
Just bought it using the App Center. :-)

What I am missing is support for images. 

Do you plan to add this?

**Comment by davidmhewitt** [comment] 2018-01-24 16:41
Hey!

Thanks for your support. It's certainly something I plan to add, but I can't give a definite time when this would be implemented.

I already have an open issue for this, so I'll close this as a duplicate of #3.

**Closed as completed** 2018-01-24 16:41 UTC

**Comment by orschiro** [comment] 2018-01-24 19:11
Wow great! Looking forward. Images are quite essential for me. Thanks for
your hard work. :)
